package Java.GameSystem;

/**
* TestingGrounds/GameSystem/CallbackInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 11:03:58 PM CST
*/

public final class CallbackInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public Java.GameSystem.CallbackInterface value = null;

  public CallbackInterfaceHolder ()
  {
  }

  public CallbackInterfaceHolder (Java.GameSystem.CallbackInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Java.GameSystem.CallbackInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Java.GameSystem.CallbackInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Java.GameSystem.CallbackInterfaceHelper.type ();
  }

}
