package Java.GameSystem;


/**
* TestingGrounds/GameSystem/CallbackInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 11:03:59 PM CST
*/

public interface CallbackInterfaceOperations 
{
  void CreateLobGUI (String username, String gameId);
  void UpdateLobGUI (Java.GameSystem.PlayerInfo[] playerData, String gameToken);
  void startGameGUI (Java.GameSystem.PlayerInfo[] playerData, char[] charArrayList);
  void updatePlayerReadyStatus (Java.GameSystem.PlayerInfo[] playerData, boolean[] readyStatus);
  void startLobbyTimer (int durationSeconds);
  void startRoundTimer (int durationSeconds);
  void broadcastGuessedWord (Java.GameSystem.PlayerInfo[] playerData, String word, String username);
  void displayRoundWinner (Java.GameSystem.PlayerInfo[] playerData, String winnerName);
  void displayOverallWinner (Java.GameSystem.PlayerInfo[] playerData, String winnerName);
  void updateLeaderBoardGUI (Java.GameSystem.Users[] playerData);
  void displayTie ();
  void ReadyStateException ();
  void wordHasBeenGuessed (String word);
  void wordIsValid (String word);
  void wordIsInvalid (String word);
  void startRoundDelayTimer (int delaySeconds);
  void updateWaitingTimeLabel (int newSeconds);
  void updateGameSessions (Java.GameSystem.Lobbies[] sessions);
  void updateAccountsList (Java.GameSystem.Users[] playerData);
  void showHomeScreen ();
  void broadcastDisconnection (String username);
} // interface CallbackInterfaceOperations
