package Java.GameSystem;


/**
* TestingGrounds/GameSystem/CharListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 11:03:58 PM CST
*/

public final class CharListHolder implements org.omg.CORBA.portable.Streamable
{
  public char value[] = null;

  public CharListHolder ()
  {
  }

  public CharListHolder (char[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Java.GameSystem.CharListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Java.GameSystem.CharListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Java.GameSystem.CharListHelper.type ();
  }

}
