package Java.GameSystem;

/**
* TestingGrounds/GameSystem/GameServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 11:03:59 PM CST
*/

public final class GameServerHolder implements org.omg.CORBA.portable.Streamable
{
  public Java.GameSystem.GameServer value = null;

  public GameServerHolder ()
  {
  }

  public GameServerHolder (Java.GameSystem.GameServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Java.GameSystem.GameServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Java.GameSystem.GameServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Java.GameSystem.GameServerHelper.type ();
  }

}
