package Java.GameSystem;

/**
* TestingGrounds/GameSystem/GameTimeExpiredHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 11:03:58 PM CST
*/

public final class GameTimeExpiredHolder implements org.omg.CORBA.portable.Streamable
{
  public Java.GameSystem.GameTimeExpired value = null;

  public GameTimeExpiredHolder ()
  {
  }

  public GameTimeExpiredHolder (Java.GameSystem.GameTimeExpired initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Java.GameSystem.GameTimeExpiredHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Java.GameSystem.GameTimeExpiredHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Java.GameSystem.GameTimeExpiredHelper.type ();
  }

}
