package Java.GameSystem;


/**
* TestingGrounds/GameSystem/GameAlreadyActive.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 11:03:58 PM CST
*/

public final class GameAlreadyActive extends org.omg.CORBA.UserException
{

  public GameAlreadyActive ()
  {
    super(GameAlreadyActiveHelper.id());
  } // ctor


  public GameAlreadyActive (String $reason)
  {
    super(GameAlreadyActiveHelper.id() + "  " + $reason);
  } // ctor

} // class GameAlreadyActive
