package Java.GameSystem;


/**
* TestingGrounds/GameSystem/GameServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 11:03:59 PM CST
*/

public interface GameServerOperations 
{
  boolean login (String username, String password, org.omg.CORBA.StringHolder sessionToken, Java.GameSystem.CallbackInterface cbi) throws Java.GameSystem.InvalidCredentials, Java.GameSystem.AlreadyLoggedIn;
  boolean logout (String sessionToken);
  boolean adminLogin (String username, String password, org.omg.CORBA.StringHolder sessionToken, Java.GameSystem.CallbackInterface cbi) throws Java.GameSystem.InvalidCredentials, Java.GameSystem.AlreadyLoggedIn;
  boolean adminLogout (String sessionToken);
  String hostGame (String sessionToken, Java.GameSystem.CallbackInterface cbi);
  String joinRandomGame (String sessionToken, Java.GameSystem.CallbackInterface cbi) throws Java.GameSystem.NoWaitingGames;
  String joinGame (String sessionToken, String gameId) throws Java.GameSystem.InvalidGameCode, Java.GameSystem.GameAlreadyActive;
  boolean startGame (String sessionToken, String gameId) throws Java.GameSystem.LobbyTimeExpired;
  void submitWord (String sessionToken, String gameId, String word) throws Java.GameSystem.InvalidWord;
  void leaveGame (String sessionToken, String gameId);
  void leaveLobby (String sessionToken, String gameId);
  String getLetters (String sessionToken, String gameId);
  void backToHomeScreen (String sessionToken);
  void updateSecondsPerWaiting (int newSeconds);
  void editRoundTime (int newSeconds);
  void editNumRounds (int newSeconds);
  String[] viewPlayers (String name);
  boolean ping ();
  boolean isServerConnected () throws Java.GameSystem.lossConnection;
} // interface GameServerOperations
