package Java.GameSystem;

/**
* TestingGrounds/GameSystem/GameAlreadyActiveHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 11:03:58 PM CST
*/

public final class GameAlreadyActiveHolder implements org.omg.CORBA.portable.Streamable
{
  public Java.GameSystem.GameAlreadyActive value = null;

  public GameAlreadyActiveHolder ()
  {
  }

  public GameAlreadyActiveHolder (Java.GameSystem.GameAlreadyActive initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Java.GameSystem.GameAlreadyActiveHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Java.GameSystem.GameAlreadyActiveHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Java.GameSystem.GameAlreadyActiveHelper.type ();
  }

}
