package Java.GameSystem;

/**
* TestingGrounds/GameSystem/InvalidGameCodeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 11:03:58 PM CST
*/

public final class InvalidGameCodeHolder implements org.omg.CORBA.portable.Streamable
{
  public Java.GameSystem.InvalidGameCode value = null;

  public InvalidGameCodeHolder ()
  {
  }

  public InvalidGameCodeHolder (Java.GameSystem.InvalidGameCode initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Java.GameSystem.InvalidGameCodeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Java.GameSystem.InvalidGameCodeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Java.GameSystem.InvalidGameCodeHelper.type ();
  }

}
