package Java.GameSystem;

/**
* TestingGrounds/GameSystem/InvalidWordHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 11:03:58 PM CST
*/

public final class InvalidWordHolder implements org.omg.CORBA.portable.Streamable
{
  public Java.GameSystem.InvalidWord value = null;

  public InvalidWordHolder ()
  {
  }

  public InvalidWordHolder (Java.GameSystem.InvalidWord initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Java.GameSystem.InvalidWordHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Java.GameSystem.InvalidWordHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Java.GameSystem.InvalidWordHelper.type ();
  }

}
