package Java.GameSystem;


/**
* TestingGrounds/GameSystem/lossConnection.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 11:03:58 PM CST
*/

public final class lossConnection extends org.omg.CORBA.UserException
{

  public lossConnection ()
  {
    super(lossConnectionHelper.id());
  } // ctor


  public lossConnection (String $reason)
  {
    super(lossConnectionHelper.id() + "  " + $reason);
  } // ctor

} // class lossConnection
