package Java.GameSystem;

/**
* TestingGrounds/GameSystem/NoWaitingGamesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 11:03:58 PM CST
*/

public final class NoWaitingGamesHolder implements org.omg.CORBA.portable.Streamable
{
  public Java.GameSystem.NoWaitingGames value = null;

  public NoWaitingGamesHolder ()
  {
  }

  public NoWaitingGamesHolder (Java.GameSystem.NoWaitingGames initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Java.GameSystem.NoWaitingGamesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Java.GameSystem.NoWaitingGamesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Java.GameSystem.NoWaitingGamesHelper.type ();
  }

}
