package Java.GameSystem;


/**
* TestingGrounds/GameSystem/PlayerInfoListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 11:03:58 PM CST
*/

abstract public class PlayerInfoListHelper
{
  private static String  _id = "IDL:TestingGrounds/GameSystem/PlayerInfoList:1.0";

  public static void insert (org.omg.CORBA.Any a, Java.GameSystem.PlayerInfo[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Java.GameSystem.PlayerInfo[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = Java.GameSystem.PlayerInfoHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (Java.GameSystem.PlayerInfoListHelper.id (), "PlayerInfoList", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Java.GameSystem.PlayerInfo[] read (org.omg.CORBA.portable.InputStream istream)
  {
    Java.GameSystem.PlayerInfo value[] = null;
    int _len0 = istream.read_long ();
    value = new Java.GameSystem.PlayerInfo[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = Java.GameSystem.PlayerInfoHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Java.GameSystem.PlayerInfo[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      Java.GameSystem.PlayerInfoHelper.write (ostream, value[_i0]);
  }

}
