package Java.GameSystem;


/**
* TestingGrounds/GameSystem/PlayerNameListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 11:03:58 PM CST
*/

public final class PlayerNameListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public PlayerNameListHolder ()
  {
  }

  public PlayerNameListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Java.GameSystem.PlayerNameListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Java.GameSystem.PlayerNameListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Java.GameSystem.PlayerNameListHelper.type ();
  }

}
