package Java.GameSystem;

/**
* TestingGrounds/GameSystem/PlayerInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 11:03:58 PM CST
*/

public final class PlayerInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public Java.GameSystem.PlayerInfo value = null;

  public PlayerInfoHolder ()
  {
  }

  public PlayerInfoHolder (Java.GameSystem.PlayerInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Java.GameSystem.PlayerInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Java.GameSystem.PlayerInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Java.GameSystem.PlayerInfoHelper.type ();
  }

}
