package Java.GameSystem;


/**
* TestingGrounds/GameSystem/User.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 4:46:06 AM CST
*/

public final class User implements org.omg.CORBA.portable.IDLEntity
{
  public String playerId = null;
  public String username = null;
  public String sessionToken = null;
  public boolean inGame = false;
  public int roundsWon = (int)0;
  public String currentGameToken = null;

  public User ()
  {
  } // ctor

  public User (String _playerId, String _username, String _sessionToken, boolean _inGame, int _roundsWon, String _currentGameToken)
  {
    playerId = _playerId;
    username = _username;
    sessionToken = _sessionToken;
    inGame = _inGame;
    roundsWon = _roundsWon;
    currentGameToken = _currentGameToken;
  } // ctor

} // class User
