package TestingGrounds.GameSystem;


/**
* GameSystem/AlreadyLoggedIn.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 2, 2024 1:47:14 AM CST
*/

public final class AlreadyLoggedIn extends org.omg.CORBA.UserException
{

  public AlreadyLoggedIn ()
  {
    super(AlreadyLoggedInHelper.id());
  } // ctor


  public AlreadyLoggedIn (String $reason)
  {
    super(AlreadyLoggedInHelper.id() + "  " + $reason);
  } // ctor

} // class AlreadyLoggedIn
