package TestingGrounds.GameSystem;

/**
* GameSystem/AlreadyLoggedInHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Sunday, May 5, 2024 3:52:54 PM CST
*/

public final class AlreadyLoggedInHolder implements org.omg.CORBA.portable.Streamable
{
  public AlreadyLoggedIn value = null;

  public AlreadyLoggedInHolder ()
  {
  }

  public AlreadyLoggedInHolder (AlreadyLoggedIn initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AlreadyLoggedInHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AlreadyLoggedInHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AlreadyLoggedInHelper.type ();
  }

}
