package TestingGrounds.GameSystem;


/**
* GameSystem/CallbackInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 2, 2024 1:47:14 AM CST
*/

public interface CallbackInterfaceOperations 
{
  void CreateLobGUI (String username, String gameId);
  void UpdateLobGUI (String username);
  void informUser (int userPosition, String word, int score);
} // interface CallbackInterfaceOperations
