package TestingGrounds.GameSystem;

/**
* GameSystem/CallbackInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 2, 2024 1:47:14 AM CST
*/

public final class CallbackInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public CallbackInterface value = null;

  public CallbackInterfaceHolder ()
  {
  }

  public CallbackInterfaceHolder (CallbackInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CallbackInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CallbackInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CallbackInterfaceHelper.type ();
  }

}
