package TestingGrounds.GameSystem;


/**
* GameSystem/CallbackInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Sunday, May 5, 2024 3:52:54 PM CST
*/

public interface CallbackInterfaceOperations 
{
  void CreateLobGUI (String username, String gameId);
  void UpdateLobGUI (PlayerInfo[] playerData);
  void informUser (int userPosition, String word, int score);
} // interface CallbackInterfaceOperations
