package TestingGrounds.GameSystem;


/**
* GameSystem/CallbackInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 2, 2024 1:47:14 AM CST
*/

public interface CallbackInterface extends CallbackInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CallbackInterface
