package TestingGrounds.GameSystem;


/**
* TestingGrounds.GameSystem/GameServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TestingGrounds.GameSystem.idl
* Tuesday, April 23, 2024 7:31:46 PM CST
*/

public interface GameServerOperations 
{
  boolean login (String username, String password, org.omg.CORBA.StringHolder sessionToken);
  boolean logout (String sessionToken);
  String hostGame (String sessionToken);
  boolean joinRandomGame (String sessionToken);
  boolean joinGame (String sessionToken, String gameId);
  boolean startGame (String sessionToken, String gameId);
  void submitWord (String sessionToken, String gameId, String word);
  String getLetters (String sessionToken, String gameId);
} // interface GameServerOperations
