package TestingGrounds.GameSystem;


/**
* TestingGrounds.GameSystem/GameServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TestingGrounds.GameSystem.idl
* Tuesday, April 23, 2024 7:31:46 PM CST
*/

abstract public class GameServerHelper
{
  private static String  _id = "IDL:TestingGrounds.GameSystem/GameServer:1.0";

  public static void insert (org.omg.CORBA.Any a, TestingGrounds.GameSystem.GameServer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TestingGrounds.GameSystem.GameServer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (TestingGrounds.GameSystem.GameServerHelper.id (), "GameServer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TestingGrounds.GameSystem.GameServer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GameServerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TestingGrounds.GameSystem.GameServer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static TestingGrounds.GameSystem.GameServer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TestingGrounds.GameSystem.GameServer)
      return (TestingGrounds.GameSystem.GameServer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TestingGrounds.GameSystem._GameServerStub stub = new TestingGrounds.GameSystem._GameServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static TestingGrounds.GameSystem.GameServer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TestingGrounds.GameSystem.GameServer)
      return (TestingGrounds.GameSystem.GameServer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TestingGrounds.GameSystem._GameServerStub stub = new TestingGrounds.GameSystem._GameServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
