package TestingGrounds.GameSystem;


/**
* GameSystem/GameServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 2, 2024 1:47:14 AM CST
*/

public interface GameServerOperations 
{
  boolean login (String username, String password, org.omg.CORBA.StringHolder sessionToken);
  boolean logout (String sessionToken);
  String hostGame (String sessionToken, CallbackInterface gci);
  boolean joinRandomGame (String sessionToken, CallbackInterface gci);
  boolean joinGame (String sessionToken, String gameId);
  boolean startGame (String sessionToken, String gameId);
  void submitWord (String sessionToken, String gameId, String word);
  String getLetters (String sessionToken, String gameId);
} // interface GameServerOperations
