package TestingGrounds.GameSystem;

/**
* GameSystem/GameServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 2, 2024 1:47:14 AM CST
*/

public final class GameServerHolder implements org.omg.CORBA.portable.Streamable
{
  public GameServer value = null;

  public GameServerHolder ()
  {
  }

  public GameServerHolder (GameServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameServerHelper.type ();
  }

}
