package TestingGrounds.GameSystem;


/**
* GameSystem/GameServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Sunday, May 5, 2024 3:52:54 PM CST
*/

public interface GameServerOperations 
{
  boolean login (String username, String password, org.omg.CORBA.StringHolder sessionToken, CallbackInterface cbi);
  boolean logout (String sessionToken);
  String hostGame (String sessionToken, CallbackInterface cbi);
  boolean joinRandomGame (String sessionToken, CallbackInterface cbi);
  boolean joinGame (String sessionToken, String gameId);
  boolean startGame (String sessionToken, String gameId);
  void submitWord (String sessionToken, String gameId, String word);
  String getLetters (String sessionToken, String gameId);
} // interface GameServerOperations
