package TestingGrounds.GameSystem;


/**
* GameSystem/InvalidWord.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 2, 2024 1:47:14 AM CST
*/

public final class InvalidWord extends org.omg.CORBA.UserException
{

  public InvalidWord ()
  {
    super(InvalidWordHelper.id());
  } // ctor


  public InvalidWord (String $reason)
  {
    super(InvalidWordHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidWord
