package TestingGrounds.GameSystem;


/**
* GameSystem/PlayerInfoListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Sunday, May 5, 2024 3:52:54 PM CST
*/

public final class PlayerInfoListHolder implements org.omg.CORBA.portable.Streamable
{
  public PlayerInfo value[] = null;

  public PlayerInfoListHolder ()
  {
  }

  public PlayerInfoListHolder (PlayerInfo[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PlayerInfoListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PlayerInfoListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PlayerInfoListHelper.type ();
  }

}
