package TestingGrounds.GameSystem;


/**
* TestingGrounds.GameSystem/_CallbackInterfaceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TestingGrounds.GameSystem.idl
* Tuesday, May 7, 2024 2:16:08 AM CST
*/

public class _CallbackInterfaceStub extends org.omg.CORBA.portable.ObjectImpl implements TestingGrounds.GameSystem.CallbackInterface
{

  public void CreateLobGUI (String username, String gameId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("CreateLobGUI", true);
                $out.write_string (username);
                $out.write_string (gameId);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                CreateLobGUI (username, gameId        );
            } finally {
                _releaseReply ($in);
            }
  } // CreateLobGUI

  public void UpdateLobGUI (TestingGrounds.GameSystem.PlayerInfo[] playerData)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("UpdateLobGUI", true);
                TestingGrounds.GameSystem.PlayerInfoListHelper.write ($out, playerData);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                UpdateLobGUI (playerData        );
            } finally {
                _releaseReply ($in);
            }
  } // UpdateLobGUI

  public void startGameGUI (TestingGrounds.GameSystem.PlayerInfo[] playerData, char[] charArrayList)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("startGameGUI", true);
                TestingGrounds.GameSystem.PlayerInfoListHelper.write ($out, playerData);
                TestingGrounds.GameSystem.CharListHelper.write ($out, charArrayList);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                startGameGUI (playerData, charArrayList        );
            } finally {
                _releaseReply ($in);
            }
  } // startGameGUI

  public void scoreUser (int userPosition, String word, int score)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("scoreUser", true);
                $out.write_long (userPosition);
                $out.write_string (word);
                $out.write_long (score);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                scoreUser (userPosition, word, score        );
            } finally {
                _releaseReply ($in);
            }
  } // scoreUser

  public void wordGuesses (int userPosition, String word, int score)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("wordGuesses", true);
                $out.write_long (userPosition);
                $out.write_string (word);
                $out.write_long (score);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                wordGuesses (userPosition, word, score        );
            } finally {
                _releaseReply ($in);
            }
  } // wordGuesses

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:TestingGrounds.GameSystem/CallbackInterface:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _CallbackInterfaceStub
