package TestingGrounds.GameSystem;

/**
* TestingGrounds/GameSystem/AlreadyLoggedInHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 1:56:55 PM SGT
*/

public final class AlreadyLoggedInHolder implements org.omg.CORBA.portable.Streamable
{
  public TestingGrounds.GameSystem.AlreadyLoggedIn value = null;

  public AlreadyLoggedInHolder ()
  {
  }

  public AlreadyLoggedInHolder (TestingGrounds.GameSystem.AlreadyLoggedIn initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TestingGrounds.GameSystem.AlreadyLoggedInHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TestingGrounds.GameSystem.AlreadyLoggedInHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TestingGrounds.GameSystem.AlreadyLoggedInHelper.type ();
  }

}
