package TestingGrounds.GameSystem;


/**
* TestingGrounds/GameSystem/AlreadyLoggedIn.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 10:14:50 PM SGT
*/

public final class AlreadyLoggedIn extends org.omg.CORBA.UserException
{

  public AlreadyLoggedIn ()
  {
    super(AlreadyLoggedInHelper.id());
  } // ctor


  public AlreadyLoggedIn (String $reason)
  {
    super(AlreadyLoggedInHelper.id() + "  " + $reason);
  } // ctor

} // class AlreadyLoggedIn
