package TestingGrounds.GameSystem;


/**
* TestingGrounds.GameSystem/AlreadyLoggedIn.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TestingGrounds.GameSystem.idl
* Tuesday, May 7, 2024 2:16:08 AM CST
*/

public final class AlreadyLoggedIn extends org.omg.CORBA.UserException
{

  public AlreadyLoggedIn ()
  {
    super(AlreadyLoggedInHelper.id());
  } // ctor


  public AlreadyLoggedIn (String $reason)
  {
    super(AlreadyLoggedInHelper.id() + "  " + $reason);
  } // ctor

} // class AlreadyLoggedIn
