package TestingGrounds.GameSystem;


/**
* GameSystem/CallbackInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Sunday, May 5, 2024 3:52:54 PM CST
*/

public abstract class CallbackInterfacePOA extends org.omg.PortableServer.Servant
 implements CallbackInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("CreateLobGUI", new java.lang.Integer (0));
    _methods.put ("UpdateLobGUI", new java.lang.Integer (1));
    _methods.put ("informUser", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // GameSystem/CallbackInterface/CreateLobGUI
       {
         String username = in.read_string ();
         String gameId = in.read_string ();
         this.CreateLobGUI (username, gameId);
         out = $rh.createReply();
         break;
       }

       case 1:  // GameSystem/CallbackInterface/UpdateLobGUI
       {
         PlayerInfo playerData[] = PlayerInfoListHelper.read (in);
         this.UpdateLobGUI (playerData);
         out = $rh.createReply();
         break;
       }

       case 2:  // GameSystem/CallbackInterface/informUser
       {
         int userPosition = in.read_long ();
         String word = in.read_string ();
         int score = in.read_long ();
         this.informUser (userPosition, word, score);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:GameSystem/CallbackInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CallbackInterface _this() 
  {
    return CallbackInterfaceHelper.narrow(
    super._this_object());
  }

  public CallbackInterface _this(org.omg.CORBA.ORB orb) 
  {
    return CallbackInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class CallbackInterfacePOA
