package TestingGrounds.GameSystem;


/**
* TestingGrounds.GameSystem/CallbackInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TestingGrounds.GameSystem.idl
* Thursday, May 9, 2024 12:00:39 AM CST
*/

public interface CallbackInterfaceOperations 
{
  void CreateLobGUI (String username, String gameId);
  void UpdateLobGUI (TestingGrounds.GameSystem.PlayerInfo[] playerData);
  void startGameGUI (TestingGrounds.GameSystem.PlayerInfo[] playerData, char[] charArrayList);
  void startLobbyTimer (int durationSeconds);
  void startRoundTimer (int durationSeconds);
  void broadcastGuessedWord (TestingGrounds.GameSystem.PlayerInfo[] playerData, String word, String username);
  void displayRoundWinner (String winnerName);
  void displayOverallWinner (String winnerName);
  void displayTie ();
} // interface CallbackInterfaceOperations
