package TestingGrounds.GameSystem;


/**
* TestingGrounds.GameSystem/CallbackInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TestingGrounds.GameSystem.idl
* Thursday, May 9, 2024 6:07:57 AM CST
*/

public interface CallbackInterface extends CallbackInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CallbackInterface
