package TestingGrounds.GameSystem;


/**
* TestingGrounds.GameSystem/CallbackInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TestingGrounds.GameSystem.idl
* Monday, May 13, 2024 4:59:56 AM CST
*/

public interface CallbackInterfaceOperations 
{
  void CreateLobGUI (String username, String gameId);
  void UpdateLobGUI (TestingGrounds.GameSystem.PlayerInfo[] playerData, String gameToken);
  void startGameGUI (TestingGrounds.GameSystem.PlayerInfo[] playerData, char[] charArrayList);
  void updatePlayerReadyStatus (TestingGrounds.GameSystem.PlayerInfo[] playerData, boolean[] readyStatus);
  void startLobbyTimer (int durationSeconds);
  void startRoundTimer (int durationSeconds);
  void broadcastGuessedWord (TestingGrounds.GameSystem.PlayerInfo[] playerData, String word, String username);
  void displayRoundWinner (String winnerName);
  void displayOverallWinner (String winnerName);
  void displayTie ();
  void ReadyStateException ();
  void wordHasBeenGuessed (String word);
  void wordIsValid (String word);
  void wordIsInvalid (String word);
  void startRoundDelayTimer (int delaySeconds);
  void updateWaitingTimeLabel (int newSeconds);
} // interface CallbackInterfaceOperations
