package TestingGrounds.GameSystem;


/**
* TestingGrounds/GameSystem/CallbackInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 11:03:58 PM CST
*/

abstract public class CallbackInterfaceHelper
{
  private static String  _id = "IDL:TestingGrounds/GameSystem/CallbackInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, TestingGrounds.GameSystem.CallbackInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TestingGrounds.GameSystem.CallbackInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (TestingGrounds.GameSystem.CallbackInterfaceHelper.id (), "CallbackInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TestingGrounds.GameSystem.CallbackInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CallbackInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TestingGrounds.GameSystem.CallbackInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static TestingGrounds.GameSystem.CallbackInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TestingGrounds.GameSystem.CallbackInterface)
      return (TestingGrounds.GameSystem.CallbackInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TestingGrounds.GameSystem._CallbackInterfaceStub stub = new TestingGrounds.GameSystem._CallbackInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static TestingGrounds.GameSystem.CallbackInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TestingGrounds.GameSystem.CallbackInterface)
      return (TestingGrounds.GameSystem.CallbackInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TestingGrounds.GameSystem._CallbackInterfaceStub stub = new TestingGrounds.GameSystem._CallbackInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
