package TestingGrounds.GameSystem;


/**
* TestingGrounds/GameSystem/CallbackInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 5:40:38 PM CST
*/

public interface CallbackInterface extends CallbackInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CallbackInterface
