package TestingGrounds.GameSystem;


/**
* TestingGrounds.GameSystem/CallbackInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TestingGrounds.GameSystem.idl
* Tuesday, May 7, 2024 2:16:08 AM CST
*/

public interface CallbackInterfaceOperations 
{
  void CreateLobGUI (String username, String gameId);
  void UpdateLobGUI (TestingGrounds.GameSystem.PlayerInfo[] playerData);
  void startGameGUI (TestingGrounds.GameSystem.PlayerInfo[] playerData, char[] charArrayList);
  void scoreUser (int userPosition, String word, int score);
  void wordGuesses (int userPosition, String word, int score);
} // interface CallbackInterfaceOperations
