package TestingGrounds.GameSystem;

/**
* TestingGrounds/GameSystem/CallbackInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Wednesday, May 15, 2024 8:33:40 AM SGT
*/

public final class CallbackInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public TestingGrounds.GameSystem.CallbackInterface value = null;

  public CallbackInterfaceHolder ()
  {
  }

  public CallbackInterfaceHolder (TestingGrounds.GameSystem.CallbackInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TestingGrounds.GameSystem.CallbackInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TestingGrounds.GameSystem.CallbackInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TestingGrounds.GameSystem.CallbackInterfaceHelper.type ();
  }

}
