package TestingGrounds.GameSystem;

/**
* TestingGrounds.GameSystem/GameServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TestingGrounds.GameSystem.idl
* Wednesday, May 8, 2024 9:36:43 PM CST
*/

public final class GameServerHolder implements org.omg.CORBA.portable.Streamable
{
  public TestingGrounds.GameSystem.GameServer value = null;

  public GameServerHolder ()
  {
  }

  public GameServerHolder (TestingGrounds.GameSystem.GameServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TestingGrounds.GameSystem.GameServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TestingGrounds.GameSystem.GameServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TestingGrounds.GameSystem.GameServerHelper.type ();
  }

}
