package TestingGrounds.GameSystem;


/**
* TestingGrounds.GameSystem/GameTimeExpired.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TestingGrounds.GameSystem.idl
* Wednesday, May 8, 2024 9:36:43 PM CST
*/

public final class GameTimeExpired extends org.omg.CORBA.UserException
{

  public GameTimeExpired ()
  {
    super(GameTimeExpiredHelper.id());
  } // ctor


  public GameTimeExpired (String $reason)
  {
    super(GameTimeExpiredHelper.id() + "  " + $reason);
  } // ctor

} // class GameTimeExpired
