package TestingGrounds.GameSystem;


/**
* TestingGrounds/GameSystem/GameSessionListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 9:39:16 PM CST
*/

public final class GameSessionListHolder implements org.omg.CORBA.portable.Streamable
{
  public TestingGrounds.GameSystem.Lobbies value[] = null;

  public GameSessionListHolder ()
  {
  }

  public GameSessionListHolder (TestingGrounds.GameSystem.Lobbies[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TestingGrounds.GameSystem.GameSessionListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TestingGrounds.GameSystem.GameSessionListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TestingGrounds.GameSystem.GameSessionListHelper.type ();
  }

}
