package TestingGrounds.GameSystem;


/**
* TestingGrounds/GameSystem/GameTimeExpired.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 2:27:42 AM CST
*/

public final class GameTimeExpired extends org.omg.CORBA.UserException
{

  public GameTimeExpired ()
  {
    super(GameTimeExpiredHelper.id());
  } // ctor


  public GameTimeExpired (String $reason)
  {
    super(GameTimeExpiredHelper.id() + "  " + $reason);
  } // ctor

} // class GameTimeExpired
