package TestingGrounds.GameSystem;


import java.sql.SQLException;

/**
* TestingGrounds/GameSystem/GameServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 1:56:55 PM SGT
*/

public interface GameServerOperations 
{
  boolean login (String username, String password, org.omg.CORBA.StringHolder sessionToken, TestingGrounds.GameSystem.CallbackInterface cbi) throws TestingGrounds.GameSystem.InvalidCredentials, TestingGrounds.GameSystem.AlreadyLoggedIn;
  boolean logout (String sessionToken);
  String hostGame (String sessionToken, TestingGrounds.GameSystem.CallbackInterface cbi) throws SQLException;
  String joinRandomGame (String sessionToken, TestingGrounds.GameSystem.CallbackInterface cbi) throws TestingGrounds.GameSystem.NoWaitingGames, SQLException;
  String joinGame (String sessionToken, String gameId) throws TestingGrounds.GameSystem.InvalidGameCode, TestingGrounds.GameSystem.GameAlreadyActive, SQLException;
  boolean startGame (String sessionToken, String gameId) throws TestingGrounds.GameSystem.LobbyTimeExpired, SQLException;
  void submitWord (String sessionToken, String gameId, String word) throws TestingGrounds.GameSystem.InvalidWord, SQLException;
  void leaveGame (String sessionToken, String gameId) throws SQLException;
  void leaveLobby (String sessionToken, String gameId) throws SQLException;
  String getLetters (String sessionToken, String gameId);
  void updateSecondsPerWaiting (int newSeconds);
  boolean ping ();
  boolean isServerConnected () throws TestingGrounds.GameSystem.lossConnection;
} // interface GameServerOperations
