package TestingGrounds.GameSystem;


/**
* TestingGrounds.GameSystem/GameAlreadyActive.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TestingGrounds.GameSystem.idl
* Wednesday, May 8, 2024 9:36:43 PM CST
*/

public final class GameAlreadyActive extends org.omg.CORBA.UserException
{

  public GameAlreadyActive ()
  {
    super(GameAlreadyActiveHelper.id());
  } // ctor


  public GameAlreadyActive (String $reason)
  {
    super(GameAlreadyActiveHelper.id() + "  " + $reason);
  } // ctor

} // class GameAlreadyActive
