package TestingGrounds.GameSystem;

/**
* TestingGrounds.GameSystem/GameAlreadyActiveHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TestingGrounds.GameSystem.idl
* Wednesday, May 8, 2024 9:36:43 PM CST
*/

public final class GameAlreadyActiveHolder implements org.omg.CORBA.portable.Streamable
{
  public TestingGrounds.GameSystem.GameAlreadyActive value = null;

  public GameAlreadyActiveHolder ()
  {
  }

  public GameAlreadyActiveHolder (TestingGrounds.GameSystem.GameAlreadyActive initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TestingGrounds.GameSystem.GameAlreadyActiveHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TestingGrounds.GameSystem.GameAlreadyActiveHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TestingGrounds.GameSystem.GameAlreadyActiveHelper.type ();
  }

}
