package TestingGrounds.GameSystem;


/**
* TestingGrounds.GameSystem/GameServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TestingGrounds.GameSystem.idl
* Monday, May 13, 2024 4:59:56 AM CST
*/

public interface GameServer extends GameServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GameServer
