package TestingGrounds.GameSystem;


/**
* TestingGrounds/GameSystem/GameServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 8:51:00 PM CST
*/

public interface GameServerOperations 
{
  boolean login (String username, String password, org.omg.CORBA.StringHolder sessionToken, TestingGrounds.GameSystem.CallbackInterface cbi) throws TestingGrounds.GameSystem.InvalidCredentials, TestingGrounds.GameSystem.AlreadyLoggedIn;
  boolean logout (String sessionToken);
  boolean adminLogin (String username, String password, org.omg.CORBA.StringHolder sessionToken, TestingGrounds.GameSystem.CallbackInterface cbi) throws TestingGrounds.GameSystem.InvalidCredentials, TestingGrounds.GameSystem.AlreadyLoggedIn;
  boolean adminLogout (String sessionToken);
  String hostGame (String sessionToken, TestingGrounds.GameSystem.CallbackInterface cbi);
  String joinRandomGame (String sessionToken, TestingGrounds.GameSystem.CallbackInterface cbi) throws TestingGrounds.GameSystem.NoWaitingGames;
  String joinGame (String sessionToken, String gameId) throws TestingGrounds.GameSystem.InvalidGameCode, TestingGrounds.GameSystem.GameAlreadyActive;
  boolean startGame (String sessionToken, String gameId) throws TestingGrounds.GameSystem.LobbyTimeExpired;
  void submitWord (String sessionToken, String gameId, String word) throws TestingGrounds.GameSystem.InvalidWord;
  void leaveGame (String sessionToken, String gameId);
  void leaveLobby (String sessionToken, String gameId);
  String getLetters (String sessionToken, String gameId);
  void backToHomeScreen (String sessionToken);
  void updateSecondsPerWaiting (int newSeconds);
  void editRoundTime (int newSeconds);
  void editNumRounds (int newSeconds);
  void viewPlayers (String name);
  boolean ping ();
  boolean isServerConnected () throws TestingGrounds.GameSystem.lossConnection;
} // interface GameServerOperations
