package TestingGrounds.GameSystem;

/**
* TestingGrounds/GameSystem/GameTimeExpiredHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 2:27:42 AM CST
*/

public final class GameTimeExpiredHolder implements org.omg.CORBA.portable.Streamable
{
  public TestingGrounds.GameSystem.GameTimeExpired value = null;

  public GameTimeExpiredHolder ()
  {
  }

  public GameTimeExpiredHolder (TestingGrounds.GameSystem.GameTimeExpired initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TestingGrounds.GameSystem.GameTimeExpiredHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TestingGrounds.GameSystem.GameTimeExpiredHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TestingGrounds.GameSystem.GameTimeExpiredHelper.type ();
  }

}
