package TestingGrounds.GameSystem;


/**
* TestingGrounds.GameSystem/InvalidCredentials.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TestingGrounds.GameSystem.idl
* Tuesday, May 7, 2024 2:16:08 AM CST
*/

public final class InvalidCredentials extends org.omg.CORBA.UserException
{

  public InvalidCredentials ()
  {
    super(InvalidCredentialsHelper.id());
  } // ctor


  public InvalidCredentials (String $reason)
  {
    super(InvalidCredentialsHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidCredentials
