package TestingGrounds.GameSystem;

/**
* TestingGrounds/GameSystem/InvalidCredentialsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Wednesday, May 15, 2024 8:33:40 AM SGT
*/

public final class InvalidCredentialsHolder implements org.omg.CORBA.portable.Streamable
{
  public TestingGrounds.GameSystem.InvalidCredentials value = null;

  public InvalidCredentialsHolder ()
  {
  }

  public InvalidCredentialsHolder (TestingGrounds.GameSystem.InvalidCredentials initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TestingGrounds.GameSystem.InvalidCredentialsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TestingGrounds.GameSystem.InvalidCredentialsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TestingGrounds.GameSystem.InvalidCredentialsHelper.type ();
  }

}
