package TestingGrounds.GameSystem;


/**
* TestingGrounds/GameSystem/InvalidGameCode.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 4:50:42 PM CST
*/

public final class InvalidGameCode extends org.omg.CORBA.UserException
{

  public InvalidGameCode ()
  {
    super(InvalidGameCodeHelper.id());
  } // ctor


  public InvalidGameCode (String $reason)
  {
    super(InvalidGameCodeHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidGameCode
