package TestingGrounds.GameSystem;


/**
* TestingGrounds.GameSystem/InvalidGameCode.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TestingGrounds.GameSystem.idl
* Tuesday, May 7, 2024 2:16:08 AM CST
*/

public final class InvalidGameCode extends org.omg.CORBA.UserException
{

  public InvalidGameCode ()
  {
    super(InvalidGameCodeHelper.id());
  } // ctor


  public InvalidGameCode (String $reason)
  {
    super(InvalidGameCodeHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidGameCode
