package TestingGrounds.GameSystem;


/**
* TestingGrounds/GameSystem/InvalidCredentials.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 1:56:55 PM SGT
*/

public final class InvalidCredentials extends org.omg.CORBA.UserException
{

  public InvalidCredentials ()
  {
    super(InvalidCredentialsHelper.id());
  } // ctor


  public InvalidCredentials (String $reason)
  {
    super(InvalidCredentialsHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidCredentials
