package TestingGrounds.GameSystem;

/**
* TestingGrounds.GameSystem/InvalidGameCodeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TestingGrounds.GameSystem.idl
* Thursday, May 9, 2024 6:07:57 AM CST
*/

public final class InvalidGameCodeHolder implements org.omg.CORBA.portable.Streamable
{
  public TestingGrounds.GameSystem.InvalidGameCode value = null;

  public InvalidGameCodeHolder ()
  {
  }

  public InvalidGameCodeHolder (TestingGrounds.GameSystem.InvalidGameCode initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TestingGrounds.GameSystem.InvalidGameCodeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TestingGrounds.GameSystem.InvalidGameCodeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TestingGrounds.GameSystem.InvalidGameCodeHelper.type ();
  }

}
