package TestingGrounds.GameSystem;


/**
* TestingGrounds/GameSystem/InvalidWord.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Wednesday, May 15, 2024 8:33:40 AM SGT
*/

public final class InvalidWord extends org.omg.CORBA.UserException
{

  public InvalidWord ()
  {
    super(InvalidWordHelper.id());
  } // ctor


  public InvalidWord (String $reason)
  {
    super(InvalidWordHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidWord
