package TestingGrounds.GameSystem;

/**
* TestingGrounds.GameSystem/InvalidWordHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TestingGrounds.GameSystem.idl
* Wednesday, May 8, 2024 9:36:43 PM CST
*/

public final class InvalidWordHolder implements org.omg.CORBA.portable.Streamable
{
  public TestingGrounds.GameSystem.InvalidWord value = null;

  public InvalidWordHolder ()
  {
  }

  public InvalidWordHolder (TestingGrounds.GameSystem.InvalidWord initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TestingGrounds.GameSystem.InvalidWordHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TestingGrounds.GameSystem.InvalidWordHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TestingGrounds.GameSystem.InvalidWordHelper.type ();
  }

}
