package TestingGrounds.GameSystem;


/**
* TestingGrounds/GameSystem/Lobbies.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 11:03:58 PM CST
*/

public final class Lobbies implements org.omg.CORBA.portable.IDLEntity
{
  public String gameToken = null;
  public int maxPlayers = (int)0;
  public int winningRounds = (int)0;
  public int lobbyWaitingTime = (int)0;
  public int durationPerRound = (int)0;
  public int delayPerRound = (int)0;
  public String status = null;
  public int playerCount = (int)0;

  public Lobbies ()
  {
  } // ctor

  public Lobbies (String _gameToken, int _maxPlayers, int _winningRounds, int _lobbyWaitingTime, int _durationPerRound, int _delayPerRound, String _status, int _playerCount)
  {
    gameToken = _gameToken;
    maxPlayers = _maxPlayers;
    winningRounds = _winningRounds;
    lobbyWaitingTime = _lobbyWaitingTime;
    durationPerRound = _durationPerRound;
    delayPerRound = _delayPerRound;
    status = _status;
    playerCount = _playerCount;
  } // ctor

} // class Lobbies
