package TestingGrounds.GameSystem;

/**
* TestingGrounds/GameSystem/LobbyTimeExpiredHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 9:39:16 PM CST
*/

public final class LobbyTimeExpiredHolder implements org.omg.CORBA.portable.Streamable
{
  public TestingGrounds.GameSystem.LobbyTimeExpired value = null;

  public LobbyTimeExpiredHolder ()
  {
  }

  public LobbyTimeExpiredHolder (TestingGrounds.GameSystem.LobbyTimeExpired initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TestingGrounds.GameSystem.LobbyTimeExpiredHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TestingGrounds.GameSystem.LobbyTimeExpiredHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TestingGrounds.GameSystem.LobbyTimeExpiredHelper.type ();
  }

}
