package TestingGrounds.GameSystem;


/**
* TestingGrounds.GameSystem/LobbyTimeExpired.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TestingGrounds.GameSystem.idl
* Tuesday, May 7, 2024 2:16:08 AM CST
*/

public final class LobbyTimeExpired extends org.omg.CORBA.UserException
{

  public LobbyTimeExpired ()
  {
    super(LobbyTimeExpiredHelper.id());
  } // ctor


  public LobbyTimeExpired (String $reason)
  {
    super(LobbyTimeExpiredHelper.id() + "  " + $reason);
  } // ctor

} // class LobbyTimeExpired
