package TestingGrounds.GameSystem;


/**
* TestingGrounds.GameSystem/lossConnection.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TestingGrounds.GameSystem.idl
* Monday, May 13, 2024 4:59:56 AM CST
*/

public final class lossConnection extends org.omg.CORBA.UserException
{

  public lossConnection ()
  {
    super(lossConnectionHelper.id());
  } // ctor


  public lossConnection (String $reason)
  {
    super(lossConnectionHelper.id() + "  " + $reason);
  } // ctor

} // class lossConnection
