package TestingGrounds.GameSystem;

/**
* TestingGrounds.GameSystem/lossConnectionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TestingGrounds.GameSystem.idl
* Tuesday, May 7, 2024 2:16:08 AM CST
*/

public final class lossConnectionHolder implements org.omg.CORBA.portable.Streamable
{
  public TestingGrounds.GameSystem.lossConnection value = null;

  public lossConnectionHolder ()
  {
  }

  public lossConnectionHolder (TestingGrounds.GameSystem.lossConnection initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TestingGrounds.GameSystem.lossConnectionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TestingGrounds.GameSystem.lossConnectionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TestingGrounds.GameSystem.lossConnectionHelper.type ();
  }

}
