package TestingGrounds.GameSystem;

/**
* TestingGrounds.GameSystem/NoWaitingGamesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TestingGrounds.GameSystem.idl
* Wednesday, May 8, 2024 9:36:43 PM CST
*/

public final class NoWaitingGamesHolder implements org.omg.CORBA.portable.Streamable
{
  public TestingGrounds.GameSystem.NoWaitingGames value = null;

  public NoWaitingGamesHolder ()
  {
  }

  public NoWaitingGamesHolder (TestingGrounds.GameSystem.NoWaitingGames initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TestingGrounds.GameSystem.NoWaitingGamesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TestingGrounds.GameSystem.NoWaitingGamesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TestingGrounds.GameSystem.NoWaitingGamesHelper.type ();
  }

}
