package TestingGrounds.GameSystem;


/**
* TestingGrounds.GameSystem/NoWaitingGames.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TestingGrounds.GameSystem.idl
* Monday, May 13, 2024 4:59:56 AM CST
*/

public final class NoWaitingGames extends org.omg.CORBA.UserException
{

  public NoWaitingGames ()
  {
    super(NoWaitingGamesHelper.id());
  } // ctor


  public NoWaitingGames (String $reason)
  {
    super(NoWaitingGamesHelper.id() + "  " + $reason);
  } // ctor

} // class NoWaitingGames
