package TestingGrounds.GameSystem;


/**
* TestingGrounds/GameSystem/NoWaitingGames.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 4:53:27 AM CST
*/

public final class NoWaitingGames extends org.omg.CORBA.UserException
{

  public NoWaitingGames ()
  {
    super(NoWaitingGamesHelper.id());
  } // ctor


  public NoWaitingGames (String $reason)
  {
    super(NoWaitingGamesHelper.id() + "  " + $reason);
  } // ctor

} // class NoWaitingGames
