package TestingGrounds.GameSystem;


/**
* TestingGrounds/GameSystem/PlayerInfoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 7:06:53 PM CST
*/

abstract public class PlayerInfoHelper
{
  private static String  _id = "IDL:TestingGrounds/GameSystem/PlayerInfo:1.0";

  public static void insert (org.omg.CORBA.Any a, TestingGrounds.GameSystem.PlayerInfo that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TestingGrounds.GameSystem.PlayerInfo extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [5];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "sessionToken",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "username",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[2] = new org.omg.CORBA.StructMember (
            "position",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[3] = new org.omg.CORBA.StructMember (
            "score",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[4] = new org.omg.CORBA.StructMember (
            "roundsWon",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (TestingGrounds.GameSystem.PlayerInfoHelper.id (), "PlayerInfo", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TestingGrounds.GameSystem.PlayerInfo read (org.omg.CORBA.portable.InputStream istream)
  {
    TestingGrounds.GameSystem.PlayerInfo value = new TestingGrounds.GameSystem.PlayerInfo ();
    value.sessionToken = istream.read_string ();
    value.username = istream.read_string ();
    value.position = istream.read_long ();
    value.score = istream.read_long ();
    value.roundsWon = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TestingGrounds.GameSystem.PlayerInfo value)
  {
    ostream.write_string (value.sessionToken);
    ostream.write_string (value.username);
    ostream.write_long (value.position);
    ostream.write_long (value.score);
    ostream.write_long (value.roundsWon);
  }

}
