package TestingGrounds.GameSystem;


/**
* TestingGrounds/GameSystem/PlayerInfoListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 11:03:58 PM CST
*/

public final class PlayerInfoListHolder implements org.omg.CORBA.portable.Streamable
{
  public TestingGrounds.GameSystem.PlayerInfo value[] = null;

  public PlayerInfoListHolder ()
  {
  }

  public PlayerInfoListHolder (TestingGrounds.GameSystem.PlayerInfo[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TestingGrounds.GameSystem.PlayerInfoListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TestingGrounds.GameSystem.PlayerInfoListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TestingGrounds.GameSystem.PlayerInfoListHelper.type ();
  }

}
