package TestingGrounds.GameSystem;

/**
* GameSystem/PlayerInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Sunday, May 5, 2024 3:52:54 PM CST
*/

public final class PlayerInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public PlayerInfo value = null;

  public PlayerInfoHolder ()
  {
  }

  public PlayerInfoHolder (PlayerInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PlayerInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PlayerInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PlayerInfoHelper.type ();
  }

}
