package TestingGrounds.GameSystem;


/**
* GameSystem/PlayerInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Sunday, May 5, 2024 3:52:54 PM CST
*/

public final class PlayerInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String sessionToken = null;
  public String username = null;
  public int position = (int)0;

  public PlayerInfo ()
  {
  } // ctor

  public PlayerInfo (String _sessionToken, String _username, int _position)
  {
    sessionToken = _sessionToken;
    username = _username;
    position = _position;
  } // ctor

} // class PlayerInfo
