package TestingGrounds.GameSystem;

/**
* TestingGrounds.GameSystem/PlayerInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TestingGrounds.GameSystem.idl
* Wednesday, May 8, 2024 9:36:43 PM CST
*/

public final class PlayerInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public TestingGrounds.GameSystem.PlayerInfo value = null;

  public PlayerInfoHolder ()
  {
  }

  public PlayerInfoHolder (TestingGrounds.GameSystem.PlayerInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TestingGrounds.GameSystem.PlayerInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TestingGrounds.GameSystem.PlayerInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TestingGrounds.GameSystem.PlayerInfoHelper.type ();
  }

}
