package TestingGrounds.GameSystem;


/**
* TestingGrounds/GameSystem/PlayerInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 11:37:48 AM SGT
*/

public final class PlayerInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String sessionToken = null;
  public String username = null;
  public int position = (int)0;
  public int score = (int)0;
  public int roundsWon = (int)0;

  public PlayerInfo ()
  {
  } // ctor

  public PlayerInfo (String _sessionToken, String _username, int _position, int _score, int _roundsWon)
  {
    sessionToken = _sessionToken;
    username = _username;
    position = _position;
    score = _score;
    roundsWon = _roundsWon;
  } // ctor

} // class PlayerInfo
