package TestingGrounds.GameSystem;


/**
* TestingGrounds/GameSystem/ReadyStatusListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Wednesday, May 15, 2024 8:33:40 AM SGT
*/

public final class ReadyStatusListHolder implements org.omg.CORBA.portable.Streamable
{
  public boolean value[] = null;

  public ReadyStatusListHolder ()
  {
  }

  public ReadyStatusListHolder (boolean[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TestingGrounds.GameSystem.ReadyStatusListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TestingGrounds.GameSystem.ReadyStatusListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TestingGrounds.GameSystem.ReadyStatusListHelper.type ();
  }

}
