package TestingGrounds.GameSystem;


/**
* TestingGrounds/GameSystem/TopFiveUsersHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 4:53:27 AM CST
*/

public final class TopFiveUsersHolder implements org.omg.CORBA.portable.Streamable
{
  public TestingGrounds.GameSystem.Users value[] = null;

  public TopFiveUsersHolder ()
  {
  }

  public TopFiveUsersHolder (TestingGrounds.GameSystem.Users[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TestingGrounds.GameSystem.TopFiveUsersHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TestingGrounds.GameSystem.TopFiveUsersHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TestingGrounds.GameSystem.TopFiveUsersHelper.type ();
  }

}
