package TestingGrounds.GameSystem;


/**
* TestingGrounds/GameSystem/TopFiveUsersHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 11:37:48 AM SGT
*/

abstract public class TopFiveUsersHelper
{
  private static String  _id = "IDL:TestingGrounds/GameSystem/TopFiveUsers:1.0";

  public static void insert (org.omg.CORBA.Any a, TestingGrounds.GameSystem.Users[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TestingGrounds.GameSystem.Users[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = TestingGrounds.GameSystem.UsersHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (TestingGrounds.GameSystem.TopFiveUsersHelper.id (), "TopFiveUsers", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TestingGrounds.GameSystem.Users[] read (org.omg.CORBA.portable.InputStream istream)
  {
    TestingGrounds.GameSystem.Users value[] = null;
    int _len0 = istream.read_long ();
    value = new TestingGrounds.GameSystem.Users[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = TestingGrounds.GameSystem.UsersHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TestingGrounds.GameSystem.Users[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      TestingGrounds.GameSystem.UsersHelper.write (ostream, value[_i0]);
  }

}
