package TestingGrounds.GameSystem;


/**
* TestingGrounds/GameSystem/Users.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 10:14:50 PM SGT
*/

public final class Users implements org.omg.CORBA.portable.IDLEntity
{
  public String playerId = null;
  public String username = null;
  public String sessionToken = null;
  public boolean inGame = false;
  public int roundsWon = (int)0;
  public String currentGameToken = null;

  public Users ()
  {
  } // ctor

  public Users (String _playerId, String _username, String _sessionToken, boolean _inGame, int _roundsWon, String _currentGameToken)
  {
    playerId = _playerId;
    username = _username;
    sessionToken = _sessionToken;
    inGame = _inGame;
    roundsWon = _roundsWon;
    currentGameToken = _currentGameToken;
  } // ctor

} // class Users
