package TestingGrounds.GameSystem;

/**
* TestingGrounds/GameSystem/UserHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 4:46:06 AM CST
*/

public final class UserHolder implements org.omg.CORBA.portable.Streamable
{
  public TestingGrounds.GameSystem.User value = null;

  public UserHolder ()
  {
  }

  public UserHolder (TestingGrounds.GameSystem.User initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TestingGrounds.GameSystem.UserHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TestingGrounds.GameSystem.UserHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TestingGrounds.GameSystem.UserHelper.type ();
  }

}
