package TestingGrounds.GameSystem;

/**
* TestingGrounds/GameSystem/UsersHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 4:53:27 AM CST
*/

public final class UsersHolder implements org.omg.CORBA.portable.Streamable
{
  public TestingGrounds.GameSystem.Users value = null;

  public UsersHolder ()
  {
  }

  public UsersHolder (TestingGrounds.GameSystem.Users initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TestingGrounds.GameSystem.UsersHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TestingGrounds.GameSystem.UsersHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TestingGrounds.GameSystem.UsersHelper.type ();
  }

}
