package TestingGrounds.GameSystem;


/**
* TestingGrounds/GameSystem/UsersHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameSystem.idl
* Thursday, May 16, 2024 10:14:50 PM SGT
*/

abstract public class UsersHelper
{
  private static String  _id = "IDL:TestingGrounds/GameSystem/Users:1.0";

  public static void insert (org.omg.CORBA.Any a, TestingGrounds.GameSystem.Users that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TestingGrounds.GameSystem.Users extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [6];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "playerId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "username",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "sessionToken",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[3] = new org.omg.CORBA.StructMember (
            "inGame",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[4] = new org.omg.CORBA.StructMember (
            "roundsWon",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[5] = new org.omg.CORBA.StructMember (
            "currentGameToken",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (TestingGrounds.GameSystem.UsersHelper.id (), "Users", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TestingGrounds.GameSystem.Users read (org.omg.CORBA.portable.InputStream istream)
  {
    TestingGrounds.GameSystem.Users value = new TestingGrounds.GameSystem.Users ();
    value.playerId = istream.read_string ();
    value.username = istream.read_string ();
    value.sessionToken = istream.read_string ();
    value.inGame = istream.read_boolean ();
    value.roundsWon = istream.read_long ();
    value.currentGameToken = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TestingGrounds.GameSystem.Users value)
  {
    ostream.write_string (value.playerId);
    ostream.write_string (value.username);
    ostream.write_string (value.sessionToken);
    ostream.write_boolean (value.inGame);
    ostream.write_long (value.roundsWon);
    ostream.write_string (value.currentGameToken);
  }

}
