module GameSystem {
struct PlayerInfo {
        string sessionToken;
        string username;
        long position;
        long score;
    };

typedef sequence<PlayerInfo> PlayerInfoList;
typedef sequence<char> CharList;

interface CallbackInterface {
    void CreateLobGUI( in string username, in string gameId);
    void UpdateLobGUI( in PlayerInfoList playerData);
    void startGameGUI( in PlayerInfoList playerData, in CharList charArrayList);
    void broadcastGuessedWord ( in PlayerInfoList playerData, in string word);
    };


    interface GameServer {
        boolean login(in string username, in string password, out string sessionToken, in CallbackInterface cbi);
        boolean logout(in string sessionToken);
        string hostGame(in string sessionToken, in CallbackInterface cbi);
        string joinRandomGame(in string sessionToken, in CallbackInterface cbi);
        string joinGame(in string sessionToken, in string gameId);
        boolean startGame(in string sessionToken, in string gameId);
        void submitWord(in string sessionToken, in string gameId, in string word);
        string getLetters(in string sessionToken, in string gameId);

    };

    exception InvalidCredentials{};

    exception AlreadyLoggedIn{};

    exception InvalidWord{};

    exception GameTimeExpired{};

    exception LobbyTimeExpired{};

    exception GameAlreadyActive{};

    exception NoWaitingGames{};

    exception InvalidGameCode{};

    exception lossConnection{};

};
